import {
  boolean,
  index,
  integer,
  jsonb,
  numeric,
  pgTable,
  text,
  timestamp,
  uuid,
} from "drizzle-orm/pg-core";
import { productStatusEnum } from "./enums";

export const categories = pgTable("categories", {
  id: uuid("id").primaryKey().defaultRandom(),
  slug: text("slug").notNull().unique(),
  name: text("name").notNull(),
  description: text("description"),
  parentId: uuid("parent_id"),
  imageUrl: text("image_url"),
  sortOrder: integer("sort_order").default(0),
  isActive: boolean("is_active").default(true),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow(),
});

export const collections = pgTable("collections", {
  id: uuid("id").primaryKey().defaultRandom(),
  slug: text("slug").notNull().unique(),
  name: text("name").notNull(),
  tagline: text("tagline"),
  description: text("description"),
  imageUrl: text("image_url"),
  bannerUrl: text("banner_url"),
  sortOrder: integer("sort_order").default(0),
  isFeatured: boolean("is_featured").default(false),
  isActive: boolean("is_active").default(true),
  launchAt: timestamp("launch_at", { withTimezone: true }),
  endsAt: timestamp("ends_at", { withTimezone: true }),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow(),
});

export const products = pgTable(
  "products",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    slug: text("slug").notNull().unique(),
    name: text("name").notNull(),
    subtitle: text("subtitle"),
    description: text("description"),
    price: numeric("price", { precision: 10, scale: 2 }).notNull(),
    compareAtPrice: numeric("compare_at_price", { precision: 10, scale: 2 }),
    currency: text("currency").default("USD"),
    categoryId: uuid("category_id").references(() => categories.id, { onDelete: "set null" }),
    categoryName: text("category_name"),
    collectionId: uuid("collection_id").references(() => collections.id, { onDelete: "set null" }),
    collectionName: text("collection_name"),
    material: text("material"),
    care: text("care"),
    inventory: integer("inventory").default(0),
    lowStockThreshold: integer("low_stock_threshold").default(5),
    sku: text("sku").unique(),
    status: productStatusEnum("status").default("draft"),
    rating: numeric("rating", { precision: 2, scale: 1 }).default("5.0"),
    reviewCount: integer("review_count").default(0),
    isNew: boolean("is_new").default(false),
    isBestSeller: boolean("is_best_seller").default(false),
    isTrending: boolean("is_trending").default(false),
    isLimited: boolean("is_limited").default(false),
    badges: text("badges").array().default([]),
    tags: text("tags").array().default([]),
    weightGrams: integer("weight_grams"),
    metaTitle: text("meta_title"),
    metaDescription: text("meta_description"),
    colors: jsonb("colors").default([]),
    sizes: jsonb("sizes").default([]),
    publishedAt: timestamp("published_at", { withTimezone: true }),
    createdAt: timestamp("created_at", { withTimezone: true }).defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow(),
  },
  (table) => [
    index("idx_products_category").on(table.categoryId),
    index("idx_products_collection").on(table.collectionId),
    index("idx_products_status").on(table.status),
    index("idx_products_slug").on(table.slug),
  ],
);

export const productImages = pgTable(
  "product_images",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    productId: uuid("product_id").references(() => products.id, { onDelete: "cascade" }),
    url: text("url").notNull(),
    alt: text("alt"),
    sortOrder: integer("sort_order").default(0),
    isPrimary: boolean("is_primary").default(false),
    createdAt: timestamp("created_at", { withTimezone: true }).defaultNow(),
  },
  (table) => [index("idx_product_images_product").on(table.productId)],
);

export const reviews = pgTable(
  "reviews",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    productId: uuid("product_id").references(() => products.id, { onDelete: "cascade" }),
    customerId: uuid("customer_id"),
    author: text("author").notNull(),
    rating: integer("rating").notNull(),
    title: text("title"),
    body: text("body"),
    isVerified: boolean("is_verified").default(false),
    isPublished: boolean("is_published").default(false),
    helpful: integer("helpful").default(0),
    response: text("response"),
    responseAt: timestamp("response_at", { withTimezone: true }),
    createdAt: timestamp("created_at", { withTimezone: true }).defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow(),
  },
  (table) => [
    index("idx_reviews_product").on(table.productId),
    index("idx_reviews_published").on(table.isPublished),
  ],
);
